-- GENERATED by scripts/gen-data.ps1 from vMenu/data/BlipInfo.cs @ 49e53065 — DO NOT EDIT.
-- luacheck: ignore
local L = GetLabelText
local H = GetHashKey

local M = {}

M.vehicle_sprites = {
    [H('taxi')] = 56,
    [H('nightshark')] = 225,
    [H('rhino')] = 421,
    [H('lazer')] = 424,
    [H('besra')] = 424,
    [H('hydra')] = 424,
    [H('insurgent')] = 426,
    [H('insurgent2')] = 426,
    [H('insurgent3')] = 426,
    [H('limo2')] = 460,
    [H('blazer5')] = 512,
    [H('phantom2')] = 528,
    [H('boxville5')] = 529,
    [H('ruiner2')] = 530,
    [H('dune4')] = 531,
    [H('dune5')] = 531,
    [H('wastelander')] = 532,
    [H('voltic2')] = 533,
    [H('technical2')] = 534,
    [H('technical3')] = 534,
    [H('technical')] = 534,
    [H('apc')] = 558,
    [H('oppressor')] = 559,
    [H('oppressor2')] = 559,
    [H('halftrack')] = 560,
    [H('dune3')] = 561,
    [H('tampa3')] = 562,
    [H('trailersmall2')] = 563,
    [H('alphaz1')] = 572,
    [H('bombushka')] = 573,
    [H('havok')] = 574,
    [H('howard')] = 575,
    [H('hunter')] = 576,
    [H('microlight')] = 577,
    [H('mogul')] = 578,
    [H('molotok')] = 579,
    [H('nokota')] = 580,
    [H('pyro')] = 581,
    [H('rogue')] = 582,
    [H('starling')] = 583,
    [H('seabreeze')] = 584,
    [H('tula')] = 585,
    [H('avenger')] = 589,
    [H('stromberg')] = 595,
    [H('deluxo')] = 596,
    [H('thruster')] = 597,
    [H('khanjali')] = 598,
    [H('riot2')] = 599,
    [H('volatol')] = 600,
    [H('barrage')] = 601,
    [H('akula')] = 602,
    [H('chernobog')] = 603,
}

-- BlipInfo.GetBlipSpriteForVehicle.
function M.get_blip_sprite_for_vehicle(vehicle)
    local model = GetEntityModel(vehicle)
    if M.vehicle_sprites[model] ~= nil then
        return M.vehicle_sprites[model]
    elseif IsThisModelABike(model) then
        return 348
    elseif IsThisModelABoat(model) then
        return 427
    elseif IsThisModelAHeli(model) then
        return 422
    elseif IsThisModelAPlane(model) then
        return 423
    end
    return 225
end

return M
